// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtRbmXcBk843KOivYahYPOArTWtC9a3vA',
    appId: '1:234934569136:web:66cbcbd3abe103e7ba1375',
    messagingSenderId: '234934569136',
    projectId: 'ecommerce-70ff6',
    authDomain: 'ecommerce-70ff6.firebaseapp.com',
    storageBucket: 'ecommerce-70ff6.appspot.com',
    measurementId: 'G-3RF60EXT9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5NakHiXxEqpWP27eyfSrpM_Gw83XUYQE',
    appId: '1:234934569136:android:d08ffc86cfea909fba1375',
    messagingSenderId: '234934569136',
    projectId: 'ecommerce-70ff6',
    storageBucket: 'ecommerce-70ff6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz8gR56yuRiMI0S4d_W6Xrn5ShmAPgj2E',
    appId: '1:234934569136:ios:b1c13200fec422f9ba1375',
    messagingSenderId: '234934569136',
    projectId: 'ecommerce-70ff6',
    storageBucket: 'ecommerce-70ff6.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz8gR56yuRiMI0S4d_W6Xrn5ShmAPgj2E',
    appId: '1:234934569136:ios:4ca049904803e222ba1375',
    messagingSenderId: '234934569136',
    projectId: 'ecommerce-70ff6',
    storageBucket: 'ecommerce-70ff6.appspot.com',
    iosBundleId: 'com.example.flutter1.RunnerTests',
  );
}
